[package]
name = "tempus"
version = "0.1.0"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]
description = "time"
license = "MIT OR Apache-2.0"

[dependencies]
libc = { version = "0.2", optional = true }
