[package]
name = "tempus"
version = "0.2.3"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]
description = "time"
license = "MIT OR Apache-2.0"

[lib]
name = "time"

[dependencies]
idem = "0.1"
libc = { version = "0.2", default-features = false, optional = true }
